#!/bin/bash

#PBS -l nodes=1:ppn=12,vmem=130gb,walltime=1:00:00
#PBS -N pRF
#PBS -V

mkdir -p prf/prf_surfaces prf/surfaces

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

echo "compiled/main"
time singularity exec -e docker://davhunt/wb_freesurfer:mcr-r2019a ./compiled/main

echo "creat_curv.lpy"
time singularity exec -e docker://brainlife/dipy:0.16.0 ./create_curv.py

#rm -f prf_results.mat

echo "and create_vtks"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./create_vtks.sh $fsdir
