#!/bin/bash

#PBS -l nodes=1:ppn=12,vmem=130gb,walltime=96:00:00
#PBS -N pRF
#PBS -V

mkdir -p prf/prf_surfaces prf/surfaces

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

echo "run PRF and remove medial wall in HCP surfaces"
time singularity exec -e docker://davhunt/wb_freesurfer:mcr-r2019a ./compiled/main
if [ ! -s ./prf/prf_surfaces/lh.polarAngle.gii ];
then
	echo "output missing"
	exit 1
fi

echo "and create vtks"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./create_vtks.sh
